"""Add name to AnalysisResult

Revision ID: 7970a8219a0c
Revises: 88bdb056860a
Create Date: 2025-06-10 16:01:48.818291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7970a8219a0c'
down_revision = '88bdb056860a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False, server_default='未命名分析'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
