"""Add AnalysisResult and AnalysisChart models

Revision ID: 88bdb056860a
Revises: 8b8e32d5b08c
Create Date: 2025-06-10 15:51:31.788480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bdb056860a'
down_revision = '8b8e32d5b08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('report_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['conversion_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_results_task_id'), ['task_id'], unique=False)

    op.create_table('analysis_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chart_data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['analysis_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_charts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_charts_result_id'), ['result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_charts_result_id'))

    op.drop_table('analysis_charts')
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_results_task_id'))

    op.drop_table('analysis_results')
    # ### end Alembic commands ###
