"""Finalize conversion models

Revision ID: 8b8e32d5b08c
Revises: 
Create Date: 2025-06-10 14:58:16.497475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8b8e32d5b08c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('dataset_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('parameters', sqlite.JSON(), nullable=True),
    sa.Column('results', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
